mysql:
  username: root
  password: root
  address: "localhost:3306"
  database: test

oracle:
  username: act
  password: act
  address: "localhost:1521"
  sid: wlzf

project:
  db: mysql                  # oracle , mysql
  dir: /mnt/d/dev/java/ideawork
  name: antserv
  pkg: cn.zft.antserv
  html: /mnt/d/dev/web/heyui/html
  exclude:
   - sys_